services:
  # backend:
  #   build:
  #     context: ./backend
  #   container_name: crowdfunding-backend-service
  #   environment:
  #     - GO_ENV=development
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: crowdfunding-frontend-service
  #   environment:
  #     - API_URL=http://backend:8080/api
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
    
  db:
    image: mysql:8.0
    container_name: crowdfunding-db-service
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ${PWD}/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crowdfundingapp-network

volumes:
  db_data:

networks:
  crowdfundingapp-network:
    driver: bridge